### ISSUE TITLE
Create gitpod.yml

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#939]
To facilitate development via [Gitpod](https://www.gitpod.io/), as per [their docs](https://www.gitpod.io/docs/).

**Comment by Daniel-Mietchen** [comment]
Should probably be something like this:

```YAML
image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: pip install -r requirements.txt # runs during prebuild
  command: python runserver.py

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 8100
    onOpen: open-browser
```
